services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 4000:8080
    networks:
      - mattzip-network
    restart: unless-stopped

  mattzip-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
      args:
        - SEARXNG_API_URL=http://searxng:8080
    depends_on:
      - searxng
    ports:
      - 3001:3001
    volumes:
      - backend-dbstore:/home/mattzip/data
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - mattzip-network
    restart: unless-stopped

networks:
  mattzip-network:

volumes:
  backend-dbstore: